-- =============================================================================
-- Customer Purchase Behavior Analytics
-- Database: PostgreSQL
-- Author: Jibek Gupta
-- Description: Business-focused SQL queries analyzing customer segments,
--              purchase behavior, discount patterns, and loyalty metrics.
-- =============================================================================


-- Preview: quick sanity check on the data
SELECT * FROM customer
LIMIT 15;


-- =============================================================================
-- SECTION 1: REVENUE ANALYSIS
-- =============================================================================

-- Q1. What is the total revenue generated by male vs. female customers?
--     Baseline segmentation to understand gender-driven revenue split.
SELECT
    gender,
    COUNT(customer_id)                          AS total_customers,
    ROUND(SUM(purchase_amount)::numeric, 2)     AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric, 2)     AS avg_purchase_amount
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average
--     purchase amount? Identifies high-value, discount-resilient buyers.
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- Q3. What is the revenue contribution of each age group?
--     Reveals which demographic segments generate the most value.
SELECT
    age_group,
    COUNT(customer_id)                          AS total_customers,
    ROUND(SUM(purchase_amount)::numeric, 2)     AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric, 2)     AS avg_spend
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- =============================================================================
-- SECTION 2: PRODUCT & CATEGORY ANALYSIS
-- =============================================================================

-- Q4. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    COUNT(customer_id)                                  AS total_purchases,
    ROUND(AVG(review_rating::numeric), 2)               AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;


-- Q5. What are the top 3 most purchased products within each category?
--     Uses DENSE_RANK window function to rank products within their category.
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id)                              AS total_orders,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        )                                               AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q6. Which 5 products have the highest percentage of purchases with discounts
--     applied? Flags items most dependent on promotions — a margin risk signal.
SELECT
    item_purchased,
    COUNT(*)                                            AS total_orders,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_orders,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*), 2
    )                                                   AS discount_rate_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC
LIMIT 5;


-- =============================================================================
-- SECTION 3: SHIPPING & BEHAVIORAL SIGNALS
-- =============================================================================

-- Q7. Compare average purchase amounts between Standard and Express shipping.
--     Higher-intent buyers may self-select into faster shipping options.
SELECT
    shipping_type,
    COUNT(customer_id)                              AS total_orders,
    ROUND(AVG(purchase_amount)::numeric, 2)         AS avg_purchase_amount,
    ROUND(SUM(purchase_amount)::numeric, 2)         AS total_revenue
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- =============================================================================
-- SECTION 4: SUBSCRIPTION & LOYALTY ANALYSIS
-- =============================================================================

-- Q8. Do subscribed customers spend more? Compare average spend and total
--     revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id)                              AS total_customers,
    ROUND(AVG(purchase_amount)::numeric, 2)         AS avg_spend,
    ROUND(SUM(purchase_amount)::numeric, 2)         AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q9. Segment customers into New, Returning, and Loyal based on their total
--     number of previous purchases. Shows the composition of the customer base.
WITH customer_segments AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases <= 1  THEN 'New'
            WHEN previous_purchases <= 10 THEN 'Returning'
            ELSE                               'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*)                                        AS number_of_customers,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct_of_base
FROM customer_segments
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- Q10. Are customers who are repeat buyers (more than 5 previous purchases)
--      also likely to subscribe? Tests relationship between loyalty and
--      subscription adoption.
SELECT
    subscription_status,
    COUNT(customer_id)                              AS repeat_buyers,
    ROUND(AVG(purchase_amount)::numeric, 2)         AS avg_spend
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- =============================================================================
-- SECTION 5: ADVANCED ANALYSIS
-- =============================================================================

-- Q11. Running total of revenue ordered by purchase amount (descending).
--      Shows how quickly revenue concentrates in high-value transactions.
SELECT
    customer_id,
    purchase_amount,
    subscription_status,
    discount_applied,
    ROUND(
        SUM(purchase_amount) OVER (
            ORDER BY purchase_amount DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )::numeric, 2
    )                                               AS running_revenue_total,
    ROUND(
        100.0 * SUM(purchase_amount) OVER (
            ORDER BY purchase_amount DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) / SUM(purchase_amount) OVER (), 2
    )                                               AS cumulative_revenue_pct
FROM customer
ORDER BY purchase_amount DESC
LIMIT 20;


-- Q12. Revenue and customer count by category AND season.
--      Pivot-style breakdown to identify which categories peak in which seasons.
SELECT
    category,
    season,
    COUNT(customer_id)                              AS total_orders,
    ROUND(SUM(purchase_amount)::numeric, 2)         AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric, 2)         AS avg_order_value
FROM customer
GROUP BY category, season
ORDER BY category, total_revenue DESC;


-- Q13. Customer value tiers using NTILE.
--      Splits customers into 4 spend quartiles by total lifetime spend.
WITH customer_spend AS (
    SELECT
        customer_id,
        SUM(purchase_amount)                         AS total_spend,
        MAX(subscription_status)                     AS subscription_status
    FROM customer
    GROUP BY customer_id
),
spend_tiers AS (
    SELECT
        customer_id,
        total_spend,
        subscription_status,
        NTILE(4) OVER (ORDER BY total_spend DESC)    AS spend_quartile
    FROM customer_spend
)
SELECT
    spend_quartile,
    CASE spend_quartile
        WHEN 1 THEN 'Top 25% Spenders'
        WHEN 2 THEN 'Upper-Mid Spenders'
        WHEN 3 THEN 'Lower-Mid Spenders'
        WHEN 4 THEN 'Bottom 25% Spenders'
    END                                             AS tier_label,
    COUNT(*)                                        AS customer_count,
    ROUND(MIN(total_spend)::numeric, 2)             AS min_total_spend,
    ROUND(MAX(total_spend)::numeric, 2)             AS max_total_spend,
    ROUND(AVG(total_spend)::numeric, 2)             AS avg_total_spend,
    ROUND(
        100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*), 1
    )                                               AS subscription_rate_pct
FROM spend_tiers
GROUP BY spend_quartile
ORDER BY spend_quartile;


-- Q14. Payment method breakdown — revenue and frequency per method.
--      Identifies preferred payment channels for targeted promotions.
SELECT
    payment_method,
    COUNT(customer_id)                              AS total_transactions,
    ROUND(SUM(purchase_amount)::numeric, 2)         AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric, 2)         AS avg_transaction_value,
    ROUND(
        100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER (), 1
    )                                               AS pct_of_transactions
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- Q15. Subscription conversion opportunity — loyal customers who are NOT yet
--      subscribed. Highest-priority targets for a subscription campaign.
SELECT
    customer_id,
    age,
    age_group,
    gender,
    previous_purchases,
    purchase_amount,
    frequency_of_purchases
FROM customer
WHERE subscription_status = 'No'
  AND previous_purchases > 10
ORDER BY previous_purchases DESC, purchase_amount DESC
LIMIT 25;
